src/Entity/Partie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PartieRepository")
 */
class Partie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Etat;

    /**
     * @ORM\Column(type="integer")
     */
    private $Score;

    /**
     * @ORM\Column(type="date")
     */
    private $Date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="parties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Quiz", inversedBy="parties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $quiz;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Question")
     */
    private $question_in_progress;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Question")
     */
    private $questions_done;

    public function __construct()
    {
        $this->questions_done = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEtat(): ?int
    {
        return $this->Etat;
    }

    public function setEtat(int $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }

    public function getScore(): ?int
    {
        return $this->Score;
    }

    public function setScore(int $Score): self
    {
        $this->Score = $Score;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getQuiz(): ?Quiz
    {
        return $this->quiz;
    }

    public function setQuiz(?Quiz $quiz): self
    {
        $this->quiz = $quiz;

        return $this;
    }

    public function getQuestionInProgress(): ?Question
    {
        return $this->question_in_progress;
    }

    public function setQuestionInProgress(?Question $question_in_progress): self
    {
        $this->question_in_progress = $question_in_progress;

        return $this;
    }

    /**
     * @return Collection|Question[]
     */
    public function getQuestionsDone(): Collection
    {
        return $this->questions_done;
    }

    public function addQuestionsDone(Question $questionsDone): self
    {
        if (!$this->questions_done->contains($questionsDone)) {
            $this->questions_done[] = $questionsDone;
        }

        return $this;
    }

    public function removeQuestionsDone(Question $questionsDone): self
    {
        if ($this->questions_done->contains($questionsDone)) {
            $this->questions_done->removeElement($questionsDone);
        }

        return $this;
    }
}

src/Entity/Question.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\QuestionRepository")
 * @Vich\Uploadable()
 *
 */
class Question implements \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="questions", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $filename;

    /**
     * @ORM\Column(type="text")
     */
    private $Libelle;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Aide;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Type;

    /**
     * @ORM\Column(type="integer")
     */
    private $Nb_Points;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Quiz", mappedBy="questions")
     */
    private $quizzes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reponse", mappedBy="question", cascade={"remove"})
     */
    private $reponses;

    public function __construct()
    {
        $this->quizzes = new ArrayCollection();
        $this->reponses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getAide(): ?string
    {
        return $this->Aide;
    }

    public function setAide(?string $Aide): self
    {
        $this->Aide = $Aide;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getNbPoints(): ?int
    {
        return $this->Nb_Points;
    }

    public function setNbPoints(int $Nb_Points): self
    {
        $this->Nb_Points = $Nb_Points;

        return $this;
    }

    /**
     * @return Collection|Quiz[]
     */
    public function getQuizzes(): Collection
    {
        return $this->quizzes;
    }

    public function addQuiz(Quiz $quiz): self
    {
        if (!$this->quizzes->contains($quiz)) {
            $this->quizzes[] = $quiz;
            $quiz->addQuestion($this);
        }

        return $this;
    }

    public function removeQuiz(Quiz $quiz): self
    {
        if ($this->quizzes->contains($quiz)) {
            $this->quizzes->removeElement($quiz);
            $quiz->removeQuestion($this);
        }

        return $this;
    }

    /**
     * @return Collection|Reponse[]
     */
    public function getReponses(): Collection
    {
        return $this->reponses;
    }

    public function addReponse(Reponse $reponse): self
    {
        if (!$this->reponses->contains($reponse)) {
            $this->reponses[] = $reponse;
            $reponse->setQuestion($this);
        }

        return $this;
    }

    public function removeReponse(Reponse $reponse): self
    {
        if ($this->reponses->contains($reponse)) {
            $this->reponses->removeElement($reponse);
            // set the owning side to null (unless already changed)
            if ($reponse->getQuestion() === $this) {
                $reponse->setQuestion(null);
            }
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Question
     */
    public function setImageFile(?File $imageFile): Question
    {
        $this->imageFile = $imageFile;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     * @return Question
     */
    public function setFilename(?string $filename): Question
    {
        $this->filename = $filename;
        return $this;
    }

    public function serialize()
    {
        return serialize($this->id);
    }

    public function unserialize($serialized)
    {
        $this->id = unserialize($serialized);

    }


}

src/Entity/Quiz.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints\DateTime;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\QuizRepository")
 * @Vich\Uploadable()
 */
class Quiz implements \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var File|null
     * @Vich\UploadableField( mapping="quizzes", fileNameProperty="filename")
     */
    private $imgFile;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $filename;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="integer")
     */
    private $Difficulte;

    /**
     * @ORM\Column(type="boolean")
     */
    private $est_Ordonne;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Partie", mappedBy="quiz")
     */
    private $parties;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="quizzes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Theme", inversedBy="quizzes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $theme;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Question", inversedBy="quizzes", cascade={"remove"})
     */
    private $questions;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->parties = new ArrayCollection();
        $this->questions = new ArrayCollection();
        $this->updated_at = new DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDifficulte(): ?int
    {
        return $this->Difficulte;
    }

    public function setDifficulte(int $Difficulte): self
    {
        $this->Difficulte = $Difficulte;

        return $this;
    }

    public function getEstOrdonne(): ?bool
    {
        return $this->est_Ordonne;
    }

    public function setEstOrdonne(bool $est_Ordonne): self
    {
        $this->est_Ordonne = $est_Ordonne;

        return $this;
    }

    /**
     * @return Collection|Partie[]
     */
    public function getParties(): Collection
    {
        return $this->parties;
    }

    public function addParty(Partie $party): self
    {
        if (!$this->parties->contains($party)) {
            $this->parties[] = $party;
            $party->setQuiz($this);
        }

        return $this;
    }

    public function removeParty(Partie $party): self
    {
        if ($this->parties->contains($party)) {
            $this->parties->removeElement($party);
            // set the owning side to null (unless already changed)
            if ($party->getQuiz() === $this) {
                $party->setQuiz(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTheme(): ?Theme
    {
        return $this->theme;
    }

    public function setTheme(?Theme $theme): self
    {
        $this->theme = $theme;

        return $this;
    }

    /**
     * @return Collection|Question[]
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->contains($question)) {
            $this->questions->removeElement($question);
        }

        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(?string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImgFile(): ?File
    {
        return $this->imgFile;
    }

    /**
     * @param File|UploadedFile|null $imgFile
     * @return Quiz
     * @throws Exception
     */
    public function setImgFile(?File $imgFile): Quiz
    {
        $this->imgFile = $imgFile;
        if ($this->imgFile instanceof UploadedFile){
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function serialize()
    {
        return serialize($this->id);
    }

    public function unserialize($serialized)
    {
        $this->id = unserialize($serialized);

    }

    public function getNbPoints() : int {
        $nb_points=0;
        foreach ($this->getQuestions() as $q){
            $nb_points+=$q->getNbPoints();
        }
        return $nb_points;
    }

    public function getLastPartie(int $userID) : ?Partie{
        $parties = $this->getParties();
        $partie_found=false;

        $lastPartie = new Partie();
        foreach ($parties as $partie){
            if ($partie->getUser()->getId() == $userID){
                if ($partie->getDate() > $lastPartie->getDate()){
                    $lastPartie = $partie;
                    $partie_found=true;
                }
            }
        }
        if($partie_found)
            return $lastPartie;
        else
            return null;
    }

}

src/Entity/Reponse.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReponseRepository")
 */
class Reponse
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Libelle;

    /**
     * @ORM\Column(type="integer")
     */
    private $Nb_Points;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Question", inversedBy="reponses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $question;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getNbPoints(): ?int
    {
        return $this->Nb_Points;
    }

    public function setNbPoints(int $Nb_Points): self
    {
        $this->Nb_Points = $Nb_Points;

        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function setQuestion(?Question $question): self
    {
        $this->question = $question;

        return $this;
    }
}

templates/game/end.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ quizz.nom }} {% endblock %}
{% block header %} {{ parent() }} {% endblock %}
{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 1200px; width: 95%;}
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>
<div class="example-wrapper">

    <div class="head row">
        <a class="back" href="{{ path('home_page') }}"><i class="fas fa-arrow-circle-left" style="font-size: 50px"></i></a>
        <div class="container">
            <div class="row">
                <h1 class="title col-8">{{ quizz.nom }}</h1>
            </div>
        </div>
    </div>
    <div class="card mb-3 bg-secondary">
        {% if quizz.filename %}
            <img src="{{ vich_uploader_asset(quizz,'imgFile') }}" class="card-img-top" alt="{{ quizz.nom }}" style="width: 100%;height: auto">
        {% endif %}
        <div class="card-body text-white">
            <div class="row justify-content-between">
                <h5 class="card-title text-white"> Thème : {{ quizz.theme.nom }}</h5>
                <h5 class="card-title text-white"> Difficulté du Quizz : {{ quizz.difficulte }}</h5>
            </div>
            {% if (partie.score / nb_points_quizz) > 0.5 %}
            <div class="row justify-content-around alert alert-success" role="alert">
            {% else %}
            <div class="row justify-content-around alert alert-danger" role="alert">
            {% endif %}
                <p class="card-text text-xl-center"> Score final : {{ partie.score }} / {{ nb_points_quizz }}</p>
            </div>
                <div class="row justify-content-center">
                <a class="btn btn-info" href="{{ path('home_page') }}"><i class="fa fa-reply-all"></i> Quitter</a>
                </div>
            <p class="card-text"><small class="text-muted">Dernière modification du quizz le {{ quizz.updatedAt.format('d/m/Y') }}.</small></p>
        </div>
    </div>
    {% endblock %}
    {% block javascripts %}
    {{ parent() }}
{% endblock %}

templates/game/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ quizz.nom }} {% endblock %}
{% block header %}{{ parent() }}{% endblock %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 1200px; width: 95%;}
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<div class="example-wrapper">

    <div class="head row">
        <a class="back" href="{{ path('home_page') }}"><i class="fas fa-arrow-circle-left" style="font-size: 50px"></i></a>
        <div class="container">
            <div class="row">
                <h1 class="title col-8">{{ quizz.nom }}</h1>
            </div>
        </div>
    </div>
    <div class="card mb-3 bg-secondary">
        {% if quizz.filename %}
        <img src="{{ vich_uploader_asset(quizz,'imgFile') }}" class="card-img-top" alt="{{ quizz.nom }}" style="width: 100%;height: auto;max-height: 50vh">
        {% endif %}
        <div class="card-body text-white">
            <div class="row justify-content-between">
                <h5 class="card-title text-white"> Thème : {{ quizz.theme.nom }}</h5>
                <h5 class="card-title text-white"> Difficulté du Quizz : {{ quizz.difficulte }}</h5>
            </div>
            <div class="row justify-content-around">
                <p class="card-text"> Score actuel : {{ partie.score }} / {{ nb_points_quizz }}</p>
                <p class="card-text"> {{ nb_questions_restantes }} questions restantes</p>
            </div>
            <p class="card-text"><small class="text-muted">Dernière modification du quizz le {{ quizz.updatedAt.format('d/m/Y') }}.</small></p>
        </div>
    </div>
    <!-- Card -->
    <div class="card bg-secondary question-div" data-is-qcm="{{ question.type=="QCM" ? 'true':'false' }}" data-infos-qcm="{{ points | json_encode }}" data-check-limit="{{ nb_reponses | json_encode }}">

        <!-- Card image -->
        <div class="view overlay">
            {% if question.filename %}
            <img class="card-img-top" src="{{ vich_uploader_asset(question,'imageFile') }}"
                 alt="{{question.libelle}}" style="width: 100%;height: auto; max-height: 40vh">
            {% endif %}
            <div class="mask rgba-white-slight"></div>
        </div>

        <!-- Card content -->
        {% if question.type == "QCM" %}
        <div class="card-body text-white answers-div" id="answers">
        {% else %}
        <div class="card-body text-white answers-div" id="answers" data-lib-correct="{{ libelle | escape('html') }}">
        {% endif %}
            <!-- Title -->
            <div class="row justify-content-center">
                <h4 class="card-title text-white">
                    {{ question.libelle }}
                {% if question.aide %}
                <button type="button" class="btn btn-secondary" style="background-color: transparent; padding: 0; border: 0"
                        data-toggle="tooltip" data-placement="top" data-html="true" title="<p>{{ question.aide }}</p>">
                    <i class="fas fa-question-circle"></i>
                </button>
                {% endif %}
                </h4>
            </div>
            {{ form(form) }}
            {% if question.type == "QCM" %}
            <div class="row justify-content-end">
                <button class="btn btn-success" id="validation"><i class="fa fa-check"></i> Valider ma réponse</button>
            </div>
            {% else %}
                <button class="btn btn-success" id="validation"><i class="fa fa-check"></i> Valider ma réponse</button>
            {% endif %}
        </div>
    </div>
    <!-- Card -->
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('game')}}
{% endblock %}