src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = ["ROLE_USER"];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="text")
     */
    private $Nom;

    /**
     * @ORM\Column(type="text")
     */
    private $Prenom;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Partie", mappedBy="user", orphanRemoval=true)
     */
    private $parties;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Quiz", mappedBy="user")
     */
    private $quizzes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Theme", mappedBy="user_id")
     */
    private $themes;

    public function __construct()
    {
        $this->parties = new ArrayCollection();
        $this->quizzes = new ArrayCollection();
        $this->themes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    /**
     * @return Collection|Partie[]
     */
    public function getParties(): Collection
    {
        return $this->parties;
    }

    public function addParty(Partie $party): self
    {
        if (!$this->parties->contains($party)) {
            $this->parties[] = $party;
            $party->setUser($this);
        }

        return $this;
    }

    public function removeParty(Partie $party): self
    {
        if ($this->parties->contains($party)) {
            $this->parties->removeElement($party);
            // set the owning side to null (unless already changed)
            if ($party->getUser() === $this) {
                $party->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Quiz[]
     */
    public function getQuizzes(): Collection
    {
        return $this->quizzes;
    }

    public function addQuiz(Quiz $quiz): self
    {
        if (!$this->quizzes->contains($quiz)) {
            $this->quizzes[] = $quiz;
            $quiz->setUser($this);
        }

        return $this;
    }

    public function removeQuiz(Quiz $quiz): self
    {
        if ($this->quizzes->contains($quiz)) {
            $this->quizzes->removeElement($quiz);
            // set the owning side to null (unless already changed)
            if ($quiz->getUser() === $this) {
                $quiz->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Theme[]
     */
    public function getThemes(): Collection
    {
        return $this->themes;
    }

    public function addTheme(Theme $theme): self
    {
        if (!$this->themes->contains($theme)) {
            $this->themes[] = $theme;
            $theme->setUserId($this);
        }

        return $this;
    }

    public function removeTheme(Theme $theme): self
    {
        if ($this->themes->contains($theme)) {
            $this->themes->removeElement($theme);
            // set the owning side to null (unless already changed)
            if ($theme->getUserId() === $this) {
                $theme->setUserId(null);
            }
        }

        return $this;
    }
    public function partieEnCours(int $idQuiz):bool {
        foreach ($this->getParties() as $partie){
            if($partie->getQuiz()->getId()===$idQuiz AND $partie->getEtat()==0){
                return true;
            }
        }
        return false;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    {% block stylesheets %}
        <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Indie+Flower&display=swap" rel="stylesheet">
        {{ encore_entry_link_tags('app') }}
    {% endblock %}
</head>

<header>
    {% block header %}
        <nav class="navbar navbar-expand-lg" role="navigation">
            <div class="container">
                {% if controller_name == "HomePageController" %}
                    <a class="navbar-brand QuizzDesignerNav" href="#body"><i class="fab fa-sketch"></i> QuizzDesigner</a>
                {% else %}
                    <a class="navbar-brand QuizzDesignerNav" href="{{ path('home_page') }}"><i class="fab fa-sketch"></i> QuizzDesigner</a>
                {% endif %}
                <div {#class="collapse navbar-collapse" id="exCollapsingNavbar"#}>
                    <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
                        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                            <div class="dropdown" data-container="body" data-toggle="popover" data-trigger="hover" data-content="Permet d'accéder à vos quizz, vos thèmes, votre historique de parties, ainsi que de vous déconnecter.">
                                <button class="btn btn-outline-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-user"></i>  {{app.user.prenom}}
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    {% if app.user.roles[0] == "ROLE_ADMIN" %}
                                        {% if controller_name == "HomePageController" %}
                                            <a class="dropdown-item" href="{{ path('admin_dash_board')}}" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="left" data-content="Accéder à vos thèmes et quizz.">Dash Board</a>
                                        {% else %}
                                            <a class="dropdown-item" href="{{ path('home_page')}}">Accueil</a>
                                        {% endif %}
                                    {% endif %}
                                    <a class="dropdown-item" href="{{ path('scores_board') }}" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="left" data-content="Accéder à l'historique de vos parties.">Historique des parties</a>
                                    <button class="btn text-primary dropdown-item" id="help-switch" value="" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="left" data-content="Désactiver les bulles d'aide comme celle-ci.">
                                        Activer l'aide
                                    </button>
                                    <a class="dropdown-item text-danger" href="{{ path('app_logout') }}">Déconnexion</a>
                                </div>
                            </div>
                        {% endif %}
                        {#<li class="dropdown order-1">
                            <button type="button" id="dropdownMenu1" data-toggle="dropdown" class="btn btn-outline-secondary dropdown-toggle">{{app.user.prenom}}</button>
                        </li>#}
                    </ul>
                </div>
            </div>
        </nav>
    {% endblock %}
</header>

<body>
{% block body %}{% endblock %}
{% block javascripts %}
    {{ encore_entry_script_tags('app') }}
{% endblock %}


{% block footer %}
    <footer class="mastfoot mt-auto border-top">
        <div class="text-center">
            <br>
            <p>Copyright &copy; QuizzDesigner made by Erwan Cado & Nicolas Desclaux - <a href="{{ path('tutorial') }}" class="text-light"> Tutoriel </a></p>
        </div>
    </footer>
{% endblock %}
</body>
</html>