src/Entity/Partie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PartieRepository")
 */
class Partie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Etat;

    /**
     * @ORM\Column(type="integer")
     */
    private $Score;

    /**
     * @ORM\Column(type="date")
     */
    private $Date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="parties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Quiz", inversedBy="parties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $quiz;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Question")
     */
    private $question_in_progress;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Question")
     */
    private $questions_done;

    public function __construct()
    {
        $this->questions_done = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEtat(): ?int
    {
        return $this->Etat;
    }

    public function setEtat(int $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }

    public function getScore(): ?int
    {
        return $this->Score;
    }

    public function setScore(int $Score): self
    {
        $this->Score = $Score;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getQuiz(): ?Quiz
    {
        return $this->quiz;
    }

    public function setQuiz(?Quiz $quiz): self
    {
        $this->quiz = $quiz;

        return $this;
    }

    public function getQuestionInProgress(): ?Question
    {
        return $this->question_in_progress;
    }

    public function setQuestionInProgress(?Question $question_in_progress): self
    {
        $this->question_in_progress = $question_in_progress;

        return $this;
    }

    /**
     * @return Collection|Question[]
     */
    public function getQuestionsDone(): Collection
    {
        return $this->questions_done;
    }

    public function addQuestionsDone(Question $questionsDone): self
    {
        if (!$this->questions_done->contains($questionsDone)) {
            $this->questions_done[] = $questionsDone;
        }

        return $this;
    }

    public function removeQuestionsDone(Question $questionsDone): self
    {
        if ($this->questions_done->contains($questionsDone)) {
            $this->questions_done->removeElement($questionsDone);
        }

        return $this;
    }
}

src/Entity/Quiz.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints\DateTime;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\QuizRepository")
 * @Vich\Uploadable()
 */
class Quiz implements \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var File|null
     * @Vich\UploadableField( mapping="quizzes", fileNameProperty="filename")
     */
    private $imgFile;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $filename;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="integer")
     */
    private $Difficulte;

    /**
     * @ORM\Column(type="boolean")
     */
    private $est_Ordonne;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Partie", mappedBy="quiz")
     */
    private $parties;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="quizzes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Theme", inversedBy="quizzes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $theme;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Question", inversedBy="quizzes", cascade={"remove"})
     */
    private $questions;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->parties = new ArrayCollection();
        $this->questions = new ArrayCollection();
        $this->updated_at = new DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDifficulte(): ?int
    {
        return $this->Difficulte;
    }

    public function setDifficulte(int $Difficulte): self
    {
        $this->Difficulte = $Difficulte;

        return $this;
    }

    public function getEstOrdonne(): ?bool
    {
        return $this->est_Ordonne;
    }

    public function setEstOrdonne(bool $est_Ordonne): self
    {
        $this->est_Ordonne = $est_Ordonne;

        return $this;
    }

    /**
     * @return Collection|Partie[]
     */
    public function getParties(): Collection
    {
        return $this->parties;
    }

    public function addParty(Partie $party): self
    {
        if (!$this->parties->contains($party)) {
            $this->parties[] = $party;
            $party->setQuiz($this);
        }

        return $this;
    }

    public function removeParty(Partie $party): self
    {
        if ($this->parties->contains($party)) {
            $this->parties->removeElement($party);
            // set the owning side to null (unless already changed)
            if ($party->getQuiz() === $this) {
                $party->setQuiz(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTheme(): ?Theme
    {
        return $this->theme;
    }

    public function setTheme(?Theme $theme): self
    {
        $this->theme = $theme;

        return $this;
    }

    /**
     * @return Collection|Question[]
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->contains($question)) {
            $this->questions->removeElement($question);
        }

        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(?string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImgFile(): ?File
    {
        return $this->imgFile;
    }

    /**
     * @param File|UploadedFile|null $imgFile
     * @return Quiz
     * @throws Exception
     */
    public function setImgFile(?File $imgFile): Quiz
    {
        $this->imgFile = $imgFile;
        if ($this->imgFile instanceof UploadedFile){
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function serialize()
    {
        return serialize($this->id);
    }

    public function unserialize($serialized)
    {
        $this->id = unserialize($serialized);

    }

    public function getNbPoints() : int {
        $nb_points=0;
        foreach ($this->getQuestions() as $q){
            $nb_points+=$q->getNbPoints();
        }
        return $nb_points;
    }

    public function getLastPartie(int $userID) : ?Partie{
        $parties = $this->getParties();
        $partie_found=false;

        $lastPartie = new Partie();
        foreach ($parties as $partie){
            if ($partie->getUser()->getId() == $userID){
                if ($partie->getDate() > $lastPartie->getDate()){
                    $lastPartie = $partie;
                    $partie_found=true;
                }
            }
        }
        if($partie_found)
            return $lastPartie;
        else
            return null;
    }

}

src/Controller/ScoresBoardController.php
<?php

namespace App\Controller;

use App\Entity\Partie;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ScoresBoardController extends AbstractController
{
    /**
     * @Route("/scores/board", name="scores_board")
     */
    public function index()
    {
        $user=$this->getUser()->getUsername();
        $user=$this->getDoctrine()->getRepository(User::class)->findOneBy(array('email'=>$user));
        $parties=$this->getDoctrine()->getRepository(Partie::class)->findBy(array('user'=>$user),array('Date'=>'DESC'));
        return $this->render('scores_board/index.html.twig', [
            'controller_name' => 'ScoresBoardController',
            'parties'=>$parties
        ]);
    }
}

templates/scores_board/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Historique de jeu{% endblock %}
{% block header %} {{ parent() }} {% endblock %}
{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 80vw; width: 95%; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
    <div class="table-responsive{-sm|-md|-lg|-xl} example-wrapper">
    <table class="table table-dark table-striped table-bordered table-hover">
        <thead class="text-xl-center bg-info" style="font-size: x-large">
        <tr>
            <th scope="col">
                Date
            </th>
            <th scope="col">
                Quizz
            </th>
            <th scope="col">
                Thème
            </th>
            <th scope="col">
                Score
            </th>
            <th scope="col">
                Etat
            </th>
            <th scope="col">
                Jouer
            </th>
        </tr>
        </thead>
        <tbody class="table-hover">

            {% for partie in parties %}
            <tr class="text-center">
                <th scope="row" class="text-xl-center">{{ partie.date.format('d/m/Y') }}</th>
                <td>{{ partie.quiz.nom }}</td>
                <td>{{ partie.quiz.theme.nom }}</td>
                <td>
                    {% if partie.etat == 1 %}
                        {% if (partie.score / partie.quiz.nbPoints) < 0.3 %}
                        <div class="alert alert-danger" role="alert">
                            {{ partie.score }}/{{ partie.quiz.nbPoints }}
                        </div>
                        {% elseif (partie.score / partie.quiz.nbPoints) > 0.6 %}
                        <div class="alert alert-success" role="alert">
                            {{ partie.score }}/{{ partie.quiz.nbPoints }}
                        </div>
                        {% else %}
                        <div class="alert alert-warning" role="alert">
                            {{ partie.score }}/{{ partie.quiz.nbPoints }}
                        </div>
                        {% endif %}
                    {% else %}
                        <div class="alert alert-info" role="alert">
                            {{ partie.score }}/{{ partie.quiz.nbPoints }}
                        </div>
                    {% endif %}
                </td>
                <td>
                    {% if partie.etat==0 %}
                        En cours
                    {% else %}
                        Terminée
                    {% endif %}
                </td>
                <td>
                    {% if partie.user.partieEnCours(partie.quiz.id) %}
                        <a href="{{ path('game',{id : partie.quiz.id}) }}" class="btn btn-primary"  data-container="body" data-toggle="popover" data-trigger="hover" data-content="Permet de reprendre la dernière partie.">
                            <i class="fa fa-play" aria-hidden="true"></i> Continuer
                        </a>
                    {% else %}
                        <a href="{{ path('game',{id : partie.quiz.id}) }}" class="btn btn-info" data-container="body" data-toggle="popover" data-trigger="hover" data-content="Permet de démarrer une partie.">
                            <i class="fa fa-play" aria-hidden="true"></i> Rejouer
                        </a>
                    {% endif %}

                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
{% endblock %}